#:import hex kivy.utils.get_color_from_hex


<Layout>:
    canvas.before:
        Rectangle:
            source: 'fundo.png'
            size: self.size  
            pos: self.pos

    orientation: 'vertical'
    # orientation: 'horizontal'

    


    spacing: '20dp'
    padding: '20dp', '40dp'

    
    TextInput:
        id: txt
        on_text_validate: self.input_text(self.text)

            
    Button:
        id: enviar_input
        background_normal: ''
        text:'envia'
        # background_color: '#5D7791'
        background_color: '#ff0073'
        size_hint: .25 , .1
        on_release: root.input_text()

        
        
    
    # BoxLayout:
    #     orientation: 'horizontal'

    #     canvas.before:
    #         Color: 
    #             rgba:  hex(#ff0073)
    #         Rectangle:
    #             size: self.size
    #             pos: self.pos
    #     size_hint_y: .05
    #     Label:
    #         text: "OpenAi ChatGPT Voz"