<TelaManager>
    Screen1:
        name: 'screen1'
        id: screen1
    Screen2:
        name: 'screen2'
        id: screen2

<Screen1>
    canvas.before:
        Rectangle:
            source: 'fundo.png'
            size: self.size  
            pos: self.pos

    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        spacing: "20dp"
        padding: '20dp', '40dp'

    
        TextInput:
            id: txt
            on_text_validate: root.manager(self.text)

            
        Button:
            background_normal: ''
            text:'envia'
            background_color: '#5D7791'
            on_release: root.load_txt()
            size_hint: .25 ,.05

        Button:
            background_normal: ''
            text:'Outra page'
            background_color: 0.998,  0.068,  0.269,  1
            on_release: root.manager.current = 'screen2'
            size_hint: .25 ,.05
        
    BoxLayout:
        orientation: 'horizontal'

        canvas.before:
            Color: 
                rgba:  0.998,  0.068,  0.269,  1
            Rectangle:
                size: self.size
                pos: self.pos
        size_hint_y: .05
        Label:
            text: "OpenAi ChatGPT Voz"

<MyButton@Button>:
    background_normal: ''

        
<Screen2>
    BoxLayout:
        orientation: 'vertical'

        Label:
            id: lb  

        Button:
            text:'Me Aperta de novo'
            on_release: root.manager.current = 'screen1'