<Layout>:
    canvas:
        Rectangle:
            source: 'fundo.png'
            size: self.size

    orientation: 'vertical'
    spacing: "20dp"
    padding: '20dp', '20dp'
    
    Label:
        text:"Seja bem vindo"
        size_hint: .05 ,.25
        

    TextInput:
        id: text_input


    Label:
        id: label 

    MyButton:

        background_color: 0.998,  0.068,  0.269,  1
        text:'Criar'
        on_release: root.load_text()

    MyButton:
        on_release: root.clear()
        text:'Clear'
        background_color: 0.698,  0.098,  0.269,  1


    MyButton:
        on_release: root.input_text()
        text:'Input Terminal'
        background_color: 0.698,  0.098,  0.269,  1



<MyButton@Button>:
    background_normal: ''

